services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque_pro_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - estoque_pro_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: estoque_pro_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - estoque_pro_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: estoque_pro_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: estoque_pro
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: estoque_user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - estoque_pro_network

  redis:
    image: redis:alpine
    container_name: estoque_pro_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - estoque_pro_network

networks:
  estoque_pro_network:
    driver: bridge

volumes:
  db_data:
    driver: local
