services:
  - type: web
    name: pw-estoque-pro
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: EstoquePro
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://pw-estoque-pro.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: error
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: estoque-pro-db
    databaseName: estoque_pro
    user: estoque_user
    region: oregon
    plan: free
    # PostgreSQL Ã© gratuito no Render
